repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
      - id: cppcheck
        args: [
          --quiet,
          --language=c++,
          --enable=all,
          --inline-suppr,
          --suppress=unmatchedSuppression,
          --suppress=unusedFunction,
          --suppress=missingInclude
        ]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        args: [
          -style=file,
          --dry-run,
          --Werror
        ]
  - repo: local
    hooks:
      - id: copyright
        name: Copyright
        entry: scripts/linter.py
        args: [
          --copyright,
          src
        ]
        pass_filenames: false
        language: python
  - repo: local
    hooks:
      - id: find
        name: Find
        entry: scripts/linter.py
        args: [
          --find,
          src
        ]
        pass_filenames: false
        language: python
