/* Copyright (c) 2018 Skyward Experimental Rocketry
 * Authors: Luca Erbetta
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 ******************************************************************************
 *                  THIS FILE IS AUTOGENERATED. DO NOT EDIT.                  *
 ******************************************************************************
 */

// Generated from:  https://docs.google.com/spreadsheets/d/12TecOmDd7Uot-MvXkCbhDJRU48-XO6s5ChKDlr4AOvI
// Autogen date:    2018-11-01 19:14:59.738365

#ifndef SRC_SHARED_BOARDS_HOMEONE_TOPICS_H
#define SRC_SHARED_BOARDS_HOMEONE_TOPICS_H

#include <stdint.h>
#include <map>
#include <string>

using std::map;
using std::string;

namespace HomeoneBoard
{
/**
 * Definition of various event topics to use in the EventBroker
 */
enum Topics : uint8_t
{
    TOPIC_ADA,
    TOPIC_DEPLOYMENT,
    TOPIC_FLIGHT_EVENTS,
    TOPIC_FMM,
    TOPIC_IGNITION,
    TOPIC_TC
};

/**
 * @brief Returns the name of the provided event
 *
 * @param event
 * @return string
 */
string getTopicString(uint8_t topic)
{
	static const map<uint8_t, string> topic_string_map{
        { TOPIC_ADA, "TOPIC_ADA" },
        { TOPIC_DEPLOYMENT, "TOPIC_DEPLOYMENT" },
        { TOPIC_FLIGHT_EVENTS, "TOPIC_FLIGHT_EVENTS" },
        { TOPIC_FMM, "TOPIC_FMM" },
        { TOPIC_IGNITION, "TOPIC_IGNITION" },
        { TOPIC_TC, "TOPIC_TC" }
	};
	auto it = topic_string_map.find(topic);
	return it == topic_string_map.end() ? "TOPIC_UNKNOWN" : it->second; 
}

}  // namespace HomeoneBoard

#endif /* SRC_SHARED_BOARDS_HOMEONE_TOPICS_H_ */
