/* Copyright (c) 2017 Skyward Experimental Rocketry
 * Authors: Alain Carlucci
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 ******************************************************************************
 *                  THIS FILE IS AUTOGENERATED. DO NOT EDIT.                  *
 ******************************************************************************
 */

// CSV File:         data/fault_list.csv
// SHA1 of CSV File: e9a518af53ac91c2e57142fda140689918338c66
// Autogen date:     2017-09-16 19:03:30.061175

#include <cstdint>

#ifndef SKYWARD_FAULT_CTRL_LIST_H
#define SKYWARD_FAULT_CTRL_LIST_H

namespace FaultCounter
{

enum class FaultCategory
{
    ANAKIN = 0,
};

enum class Fault
{
    F_ANAKIN_TEST_FAULT = 0,
};


// Usage: categoryID = FaultCounter::FaultToCategory[faultID];
static const uint32_t FaultToCategory[] = 
{
    0, 
}; /* CategoryMapping */

} /* FaultCounter */

#endif /* SKYWARD_FAULT_CTRL_LIST_H */

