#pragma once

#include <cstdint>
#include <cstring>
#include <utility>

// Enabling this imports a bunch of stuff
#ifdef USERDE_STREAM_DESERIALIZER
#include <functional>
#include <istream>
#include <map>
#include <string>
#include <type_traits>
#endif

#include "reflect.hpp"

namespace socrate
{
namespace userde
{

typedef float float32_t;
typedef double float64_t;

/**
 * Enum of possible errors generated by userde.
 */
enum class Error
{
    Success,           //< No errors generated.
    BufferTooSmall,    //< Passed buffer is too small to hold serialized data.
    TypeNameMismatch,  //< Type encoded in buffer does not match requested type.
};

/**
 * Convert an error to a human readable string.
 */
inline const char* error_to_msg(Error error)
{
    switch (error)
    {
        case Error::Success:
            return "success";
        case Error::BufferTooSmall:
            return "buffer too small";
        case Error::TypeNameMismatch:
            return "type name mismatch";
        default:
            return "";  // You happy know gcc?
    }
}

/**
 * Byte stream for internal usage.
 */
struct Stream
{
    uint8_t* buffer;

    void write(const void* value, size_t size)
    {
        memcpy(buffer, value, size);
        buffer += size;
    }

    void read(void* value, size_t size)
    {
        memcpy(value, buffer, size);
        buffer += size;
    }

    bool check(const void* value, size_t size)
    {
        bool same = memcmp(buffer, value, size) == 0;
        buffer += size;

        return same;
    }

    void write_str(const char* value) { write(value, strlen(value) + 1); }

    bool check_str(const char* value)
    {
        return check(value, strlen(value) + 1);
    }
};

template <typename T>
constexpr bool is_integral_enough =
    std::is_arithmetic<T>::value || std::is_enum<T>::value;

/**
 * Retrieve the size of a serializable type
 */
template <typename T, typename = void>
struct Serde
{
};

template <typename T, size_t I>
struct Serde<T[I], std::enable_if_t<is_integral_enough<T>>>
{
    static constexpr size_t size() { return sizeof(T[I]); };

    static void serialize(const T (&value)[I], Stream& stream)
    {
        stream.write(&value, size());
    }

    static void deserialize(T (&value)[I], Stream& stream)
    {
        stream.read(&value, size());
    }
};

template <typename T>
struct Serde<T, std::enable_if_t<is_integral_enough<T>>>
{
    static constexpr size_t size() { return sizeof(T); };

    static void serialize(const T& value, Stream& stream)
    {
        stream.write(&value, size());
    }

    static void deserialize(T& value, Stream& stream)
    {
        stream.read(&value, size());
    }
};

template <typename T>
struct Serde<T, std::enable_if_t<socrate::reflect::is_reflectable<T>>>
{
    static constexpr size_t size()
    {
        return T::reflect().fold_fields_type(
            0,
            [](size_t acc, const char* _name, auto type)
            {
                using Type = typename decltype(type)::Type;
                return acc + Serde<Type>::size();
            });
    }

    static void serialize(const T& value, Stream& stream)
    {
        T::reflect().for_each_field_const(
            value,
            [&](const char* _name, const auto& value, auto type)
            {
                using Type = typename decltype(type)::Type;
                Serde<Type>::serialize(value, stream);
            });
    }

    static void deserialize(T& value, Stream& stream)
    {
        T::reflect().for_each_field(
            value,
            [&](const char* _name, auto& value, auto type)
            {
                using Type = typename decltype(type)::Type;
                Serde<Type>::deserialize(value, stream);
            });
    }
};

/**
 * Serialize the given value inside buffer.
 *
 * @param value Value to be serialized.
 * @param buffer Output buffer.
 * @param size Size of the buffer.
 *
 * @return Error Error code.
 */
template <typename T>
Error serialize(const T& value, uint8_t* buffer, size_t size)
{
    static_assert(socrate::reflect::is_reflectable<T>,
                  "T must be reflectable!");

    if (size < Serde<T>::size())
        return Error::BufferTooSmall;

    Stream stream{buffer};

    // Write body
    Serde<T>::serialize(value, stream);

    return Error::Success;
}

/**
 * Serialize the given value inside the buffer, include the type name.
 *
 * @param value Value to be serialized.
 * @param buffer Output buffer.
 * @param size Size of the buffer.
 *
 * @return Error Error code.
 */
template <typename T>
Error serialize_with_name(T& value, uint8_t* buffer, size_t size)
{
    static_assert(socrate::reflect::is_reflectable<T>,
                  "T must be reflectable!");

    const char* type_name = T::reflect().type_name();

    // Encoded data + name + name null terminator
    if (size < Serde<T>::size() + strlen(type_name) + 1)
        return Error::BufferTooSmall;

    Stream stream{buffer};

    // Write type name
    stream.write_str(type_name);

    // Write body
    Serde<T>::serialize(value, stream);

    return Error::Success;
}

/**
 * Deserialize the given value from the buffer.
 * WARNING: Does not check for correct type in buffer!
 *
 * @param value Value to deserialize into.
 * @param buffer Input buffer.
 * @param size Size of the buffer.
 *
 * @return Error Error code.
 */
template <typename T>
Error deserialize(T& value, uint8_t* buffer, size_t size)
{
    static_assert(socrate::reflect::is_reflectable<T>,
                  "T must be reflectable!");

    if (size < Serde<T>::size())
        return Error::BufferTooSmall;

    Stream stream{buffer};

    // Read body
    Serde<T>::deserialize(value, stream);

    return Error::Success;
}

/**
 * Deserialize the given value from the buffer.
 * Checks that the type encoded in the buffer matches with what is being
 * decoded.
 *
 * @param value Value to deserialize into.
 * @param buffer Input buffer.
 * @param size Size of the buffer.
 *
 * @return Error Error code.
 */
template <typename T>
Error deserialize_with_name(T& value, uint8_t* buffer, size_t size)
{
    static_assert(socrate::reflect::is_reflectable<T>,
                  "T must be reflectable!");

    const char* type_name = T::reflect().type_name();

    // Encoded data + name + name null terminator
    if (size < Serde<T>::size() + strlen(type_name) + 1)
        return Error::BufferTooSmall;

    Stream stream{buffer};

    // Assert that type name is correct
    if (!stream.check_str(type_name))
        return Error::TypeNameMismatch;

    // Read body
    Serde<T>::deserialize(value, stream);

    return Error::Success;
}

#ifdef USERDE_STREAM_DESERIALIZER
// Mhhh yes, boilerplate
class MemBuf : public std::streambuf
{
public:
    MemBuf(const uint8_t* buffer, size_t size)
    {
        setg((char*)buffer, (char*)buffer, (char*)buffer + size);
    }
};

/**
 * Convenience implementation of an input stream that feeds on a byte buffer.
 */
class MemStream : public std::istream
{
public:
    MemStream(const uint8_t* buffer, size_t size)
        : std::istream(&membuf), membuf(buffer, size)
    {
        rdbuf(&membuf);
    }

private:
    MemBuf membuf;
};

/**
 * Automatically deserialize a stream of data and automatically dispatch types
 * to correct handler.
 */
class StreamDeserializer
{
public:
    /**
     * @brief Register a callback for a given type.
     *
     * @param f The associated callback.
     */
    template <typename T, typename F>
    void register_type(F&& f)
    {
        static_assert(socrate::reflect::is_reflectable<T>,
                      "T must be reflectable!");
        static_assert(std::is_default_constructible<T>::value,
                      "T must be default constructible!");

        std::string type_name(T::reflect().type_name());

        auto f2 = [f = std::move(f)](std::istream& is)
        {
            uint8_t buffer[Serde<T>::size()];
            is.read(reinterpret_cast<char*>(buffer), sizeof(buffer));

            Stream stream{buffer};

            T value{};

            // Read body
            Serde<T>::deserialize(value, stream);

            f(value);
        };

        types.insert({type_name, f2});
    }

    /**
     * @brief Deserialize the given stream, invoking callbacks for each
     * encountered type.
     *
     * @param is Input stream.
     */
    void deserialize(std::istream& is)
    {
        // TODO(davide.mor): Sometimes is.eof() doesn't work, why?
        while (is.peek() != -1)
        {
            std::string type_name;

            // Read null terminated name string
            while (is.peek() != 0)
                type_name += is.get();
            // Dummy null read
            is.get();

            // Invoke correct parser for this type
            (types.at(type_name))(is);
        }
    }

private:
    std::map<std::string, std::function<void(std::istream&)>> types;
};
#endif

}  // namespace userde
}  // namespace socrate
