#!/usr/bin/env bash

# Copyright (c) 2023 Skyward Experimental Rocketry
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

current_path="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"

# Target directory name
target_dir="skyward-boardcore"

# Cut the path to the target directory
while [[ "$current_path" != "/" && "$(basename "$current_path")" != "$target_dir" ]]; do
    current_path="$(dirname "$current_path")"
done

source "$current_path/scripts/sbs_implementation"

function _sbs_autocomplete() {
    declare curr_arg="${COMP_WORDS[COMP_CWORD]}"
    declare prev_arg="${COMP_WORDS[COMP_CWORD - 1]}"

    case "$prev_arg" in
    "-b" | "--build") ;&
    "-f" | "--flash") ;&
    "-t" | "--test")
        # Autocomplete options for build, flash and test
        init_dirs
        COMPREPLY=($(compgen -W "$(list --only-list)" -- "$curr_arg"))
        ;;
    *)
        # Autocomplete options for general options
        COMPREPLY=($(compgen -W "\
                -h --help      \
                -j --jobs      \
                -l --list      \
                -r --boards    \
                -b --build     \
                -f --flash     \
                -t --test      \
                -c --clean     \
                -u --configure \
                -d --debug     \
                -v --verbose   \
                -n --lint      \
                -e --edit      \
                --clang-tidy" -- "$curr_arg"))
        ;;
    esac
}

complete -F _sbs_autocomplete sbs
