
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef RESPECT_H
#define RESPECT_H

#include "mxgui/image.h"

extern const mxgui::Image respect;

#endif //RESPECT_H
